# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job_runner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='job_runner.proto',
  package='gtisc.gpl_voilation.proto',
  serialized_pb=_b('\n\x10job_runner.proto\x12\x19gtisc.gpl_voilation.proto\"\xf0\x04\n\tJobConfig\x12\x10\n\x08job_name\x18\x01 \x01(\t\x12\x42\n\ninput_type\x18\x02 \x01(\x0e\x32..gtisc.gpl_voilation.proto.JobConfig.InputType\x12\x12\n\ninput_path\x18\x03 \x01(\t\x12\x1c\n\x14\x61ndroid_jar_dir_path\x18\x04 \x01(\t\x12\x1e\n\x16\x66orce_android_jar_path\x18\x05 \x01(\t\x12\x13\n\x0b\x63onfig_path\x18\x06 \x01(\t\x12\x12\n\nresult_dir\x18\x07 \x01(\t\x12\x1b\n\rresult_suffix\x18\x0f \x01(\t:\x04.sig\x12!\n\x12\x65xpect_android_jar\x18\x10 \x01(\x08:\x05\x66\x61lse\x12\x12\n\nthread_num\x18\x11 \x01(\x05\x12\x14\n\x0csoot_out_dir\x18\x08 \x01(\t\x12\x15\n\rconsole_print\x18\t \x01(\x08\x12\x15\n\rbinary_config\x18\n \x01(\x08\x12\x1c\n\rbinary_output\x18\x0b \x01(\x08:\x05\x66\x61lse\x12\x18\n\x10keep_soot_output\x18\x0c \x01(\x08\x12\x15\n\randrosim_path\x18\r \x01(\t\x12\x18\n\x10\x64iff_method_path\x18\x0e \x01(\t\"\x90\x01\n\tInputType\x12\x07\n\x03\x41PK\x10\x00\x12\x07\n\x03\x44\x45X\x10\x01\x12\x07\n\x03JAR\x10\x02\x12\t\n\x05\x43LASS\x10\x03\x12\n\n\x06SOURCE\x10\x04\x12\x0b\n\x07\x41PK_DIR\x10\x05\x12\x0b\n\x07\x44\x45X_DIR\x10\x06\x12\x0b\n\x07JAR_DIR\x10\x07\x12\r\n\tCLASS_DIR\x10\x08\x12\x0e\n\nSOURCE_DIR\x10\t\x12\x0b\n\x07UNKNOWN\x10\n')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_JOBCONFIG_INPUTTYPE = _descriptor.EnumDescriptor(
  name='InputType',
  full_name='gtisc.gpl_voilation.proto.JobConfig.InputType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='APK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEX', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JAR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLASS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOURCE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APK_DIR', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEX_DIR', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JAR_DIR', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLASS_DIR', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOURCE_DIR', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=528,
  serialized_end=672,
)
_sym_db.RegisterEnumDescriptor(_JOBCONFIG_INPUTTYPE)


_JOBCONFIG = _descriptor.Descriptor(
  name='JobConfig',
  full_name='gtisc.gpl_voilation.proto.JobConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_name', full_name='gtisc.gpl_voilation.proto.JobConfig.job_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_type', full_name='gtisc.gpl_voilation.proto.JobConfig.input_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_path', full_name='gtisc.gpl_voilation.proto.JobConfig.input_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='android_jar_dir_path', full_name='gtisc.gpl_voilation.proto.JobConfig.android_jar_dir_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='force_android_jar_path', full_name='gtisc.gpl_voilation.proto.JobConfig.force_android_jar_path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config_path', full_name='gtisc.gpl_voilation.proto.JobConfig.config_path', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result_dir', full_name='gtisc.gpl_voilation.proto.JobConfig.result_dir', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result_suffix', full_name='gtisc.gpl_voilation.proto.JobConfig.result_suffix', index=7,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b(".sig").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expect_android_jar', full_name='gtisc.gpl_voilation.proto.JobConfig.expect_android_jar', index=8,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thread_num', full_name='gtisc.gpl_voilation.proto.JobConfig.thread_num', index=9,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='soot_out_dir', full_name='gtisc.gpl_voilation.proto.JobConfig.soot_out_dir', index=10,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='console_print', full_name='gtisc.gpl_voilation.proto.JobConfig.console_print', index=11,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='binary_config', full_name='gtisc.gpl_voilation.proto.JobConfig.binary_config', index=12,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='binary_output', full_name='gtisc.gpl_voilation.proto.JobConfig.binary_output', index=13,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keep_soot_output', full_name='gtisc.gpl_voilation.proto.JobConfig.keep_soot_output', index=14,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='androsim_path', full_name='gtisc.gpl_voilation.proto.JobConfig.androsim_path', index=15,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diff_method_path', full_name='gtisc.gpl_voilation.proto.JobConfig.diff_method_path', index=16,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOBCONFIG_INPUTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=672,
)

_JOBCONFIG.fields_by_name['input_type'].enum_type = _JOBCONFIG_INPUTTYPE
_JOBCONFIG_INPUTTYPE.containing_type = _JOBCONFIG
DESCRIPTOR.message_types_by_name['JobConfig'] = _JOBCONFIG

JobConfig = _reflection.GeneratedProtocolMessageType('JobConfig', (_message.Message,), dict(
  DESCRIPTOR = _JOBCONFIG,
  __module__ = 'job_runner_pb2'
  # @@protoc_insertion_point(class_scope:gtisc.gpl_voilation.proto.JobConfig)
  ))
_sym_db.RegisterMessage(JobConfig)


# @@protoc_insertion_point(module_scope)
